Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu14"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.box_url = config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.hostname = 'redux'

  config.vm.network "forwarded_port", guest: 80, host: 9080
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.synced_folder ".", "/project"

  config.vm.provision "shell", inline: "cd /project/scripts/ && ./provision.sh", privileged: false

  config.vm.provider "virtualbox" do |v|
    v.memory = 5024
    v.cpus = 2
  end
end
